apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "*/1 * * * *"  # chạy mỗi phút
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command: ["echo", "Hello, Kubernetes!"]
          restartPolicy: OnFailure  # Nếu gặp lỗi, chỉ restart khi Pod gặp sự cố
