apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: khainh3101/secrete_configmap:latest
    env:
    - name: CONFIG_KEY
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: config_key
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
